package com.han.startup.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
@AllArgsConstructor
public enum CustomErrorType implements ErrorType {
    // FIXME: Organize code
    CUSTOM_TEST(1000),

    CUSTOM_AWS_SDK_ERROR(1001),
    CUSTOM_AWS_SDK_INIT_FAIL(1002),
    CUSTOM_AWS_INVALID_INSTANCE_ID(1003),
    CUSTOM_AWS_S3_FILE_WRITE_FAIL(1004),
    CUSTOM_AWS_REGION_NOT_FOUND(1005, HttpStatus.BAD_REQUEST),
    CUSTOM_AWS_ECR_LIFECYCLE_POLICY_NOT_EXIST(1006, ErrorLogLevel.WARN, HttpStatus.BAD_REQUEST),
    CUSTOM_AWS_S3_AUTH_ERROR(1007, ErrorLogLevel.WARN, HttpStatus.BAD_REQUEST),

    CUSTOM_ENUM_NOT_FOUND(1011),
    CUSTOM_ENUM_NOT_A_ENUM_CLASS(1012),

    CUSTOM_AES_ENCRYPT_FAIL(1021),
    CUSTOM_AES_DECRYPT_FAIL(1022),

    CUSTOM_AUTH_LOGIN_FAIL(1031),
    CUSTOM_AUTH_UBIUSER_FAIL(1032),

    CUSTOM_MEMBER_REQUEST_PERMISSION_NOT_FOUND(1041),

    CUSTOM_AWX_INVALID_INVENTORY_SOURCE_VARS(1051, HttpStatus.BAD_REQUEST),
    CUSTOM_AWX_INVALID_INVENTORY_GROUP_ID(1052, HttpStatus.NOT_FOUND),
    CUSTOM_AWX_THERE_IS_NO_ORIGINAL_JOB_TEMPLATE(1053),
    CUSTOM_AWX_INVALID_CREDENTIAL(1054, HttpStatus.NOT_FOUND),
    CUSTOM_AWX_INVALID_INVENTORY_ID(1055, HttpStatus.NOT_FOUND),
    CUSTOM_AWX_INVALID_INVENTORY_NAME(1056, HttpStatus.NOT_FOUND),
    CUSTOM_AWX_INVALID_INVENTORY_SOURCE_NAME(1057, HttpStatus.NOT_FOUND),

    CUSTOM_COMMAND_INVOCATION_FAIL(1061, HttpStatus.BAD_REQUEST),
    CUSTOM_COMMAND_POLLING_FAIL(1062),
    CUSTOM_COMMAND_UNKNOWN_COMMAND_AGENT_TYPE(1063, HttpStatus.BAD_REQUEST),
    CUSTOM_COMMAND_GROUP_DEPLOYMENT_FAIL(1064, ErrorLogLevel.WARN),
    CUSTOM_COMMAND_SSM_NOT_SUPPORT_PLATFORM(1065, HttpStatus.BAD_REQUEST),

    CUSTOM_LOG_STREAM_FAIL_TO_GET(1071),

    CUSTOM_ORCHESTRATION_GROUP_NO_TAG_KEY(1081),
    CUSTOM_MEMBER_NO_MEMBER_GROUP(1091),

    CUSTOM_PROMETHEUS_DEPLOYMENT_FAIL(1101),
    CUSTOM_PROMETHEUS_TEMPLATE_NOT_FOUND(1102),
    CUSTOM_PROMETHEUS_FAIL_TO_LOAD_VARIABLES(1103),

    CUSTOM_PLATFORM_NOT_SUPPORT(1011, HttpStatus.BAD_REQUEST),
    CUSTOM_SERVER_INFORMATION_NO_PLATFORM_REGION_INFO(1021, HttpStatus.BAD_REQUEST),
    CUSTOM_INVOCATION_FAIL(1031, ErrorLogLevel.WARN),

    CUSTOM_ZOOKEEPER_UPDATE_FAIL(1041),
    ;

    CustomErrorType(int errorCode) {
        this(errorCode, ErrorLogLevel.ERROR);
    }

    CustomErrorType(int errorCode, ErrorLogLevel errorLogLevel) {
        this(errorCode, errorLogLevel, HttpStatus.INTERNAL_SERVER_ERROR);
    }

    CustomErrorType(int errorCode, HttpStatus httpStatus) {
        this(errorCode, ErrorLogLevel.ERROR, httpStatus);
    }

    private int errorCode;
    private ErrorLogLevel errorLogLevel;
    private HttpStatus status;
}
